language: node_js
node_js:
  - stable
install:
  - npm install
script:
  - npm test
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "rafaneri"
  - git config --local user.email "rafael.neri@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "3feaaf4cc5d2bb81db58ce3afc1e073475cc72e1"
  file: lib/**/*
  skip_cleanup: true
